try:
    # Try importing Pydantic v2
    from pydantic import BaseModel, Field
    from pydantic.version import VERSION as PYDANTIC_VERSION
    if not PYDANTIC_VERSION.startswith("2."):
        raise ImportError("Not Pydantic v2")
except ImportError:
    # Fallback to Pydantic v1
    from pydantic import BaseModel, Field
    
    
class Request(BaseModel):
    """
    Represents a request to the agent.
    Contains the input and any additional parameters.
    """
    message: str = Field(description="The input message for the agent.")
    funcional: str = Field(description="The functional area of the request.")
    session_id: str = Field(description="The session ID for tracking the request.")
    interaction_id: str = Field(description="The interaction ID for tracking the request.")
    datetime: str = Field(description="The date and time of the request.")
    

class GenerativeResult(BaseModel):
    """
    Represents the result of a generative request.
    Contains the output and any additional information.
    """
    output: str = Field(description="The output generated by the agent.")
    errors: str = Field(description="Any errors encountered during processing.")
    session_id: str = Field(description="The session ID for tracking the result.")
    interaction_id: str = Field(description="The interaction ID for tracking the result.")
    datetime: str = Field(description="The date and time of the result.")
    
class Result(Request):
    """
    Represents the result of processing a request by the agent.
    Contains the output and any additional information.
    """
    result: GenerativeResult = Field(description="The output generated by the agent.")