from abc import abstractmethod
from langchain.llms import LLM

from langgraph_supervisor_with_agents.schema.chatbot import (
    Request,
    GenerativeResult,
    Result,
)

class BaseLLM(LLM):

    def _call(self, request: Request) -> Result:
        """
        Handle the conversation by processing the request.

        Args:
            request (Request): The request containing the conversation details.

        Returns:
            str: The response generated by the LLM.
            Result: The response generated by the LLM.
        """
        self.request = request

        if not self._check_request(request):
            return Result(
                **request.model_dump(),
                result=GenerativeResult(
                    output="Invalid request",
                    errors="Request validation failed.",
                    session_id=request.session_id,
                    interaction_id=request.interaction_id,
                    datetime=request.datetime,
                ),
            )

        if not request.should_process:
            result = GenerativeResult(
                output="Not processed",
                errors="Request processing is disabled.",
                session_id=request.session_id,
                interaction_id=request.interaction_id,
                datetime=request.datetime,
            )
            return Result(**request.model_dump(), result=result)

        return Result(**request.model_dump(), result=self.run(request))

    def _check_request(self, request: Request) -> bool:
        """
        Check if the request is valid.

        Args:
            request (Request): The request to check.

        Returns:
            bool: True if the request is valid, False otherwise.
        """
        return isinstance(request, Request)

    @abstractmethod
    def run(self, request: Request) -> GenerativeResult:
        """
        Run the conversation handler with the provided request.

        Args:
            request (Request): The request containing the conversation details.

        Returns:
            GenerativeResult: The result of processing the request.
        """
        pass